// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw8u4i8maulM9CIFNyu-jgj_UMHxB8aRE',
    appId: '1:916801022458:web:12c6473c71c094bb4b9c43',
    messagingSenderId: '916801022458',
    projectId: 'beautician-50d49',
    authDomain: 'beautician-50d49.firebaseapp.com',
    storageBucket: 'beautician-50d49.firebasestorage.app',
    measurementId: 'G-7RC9ZZYJB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUNMGI0DR9qq_FtdewSk5W8uMbjmwcmfk',
    appId: '1:916801022458:android:200c499718cbfd334b9c43',
    messagingSenderId: '916801022458',
    projectId: 'beautician-50d49',
    storageBucket: 'beautician-50d49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaxvzJBs-Xk4qFKVi4a4NgkgICg3ZqFDs',
    appId: '1:916801022458:ios:8f06c5b5fe2ad8db4b9c43',
    messagingSenderId: '916801022458',
    projectId: 'beautician-50d49',
    storageBucket: 'beautician-50d49.firebasestorage.app',
    iosBundleId: 'com.beautician.beauticianApp',
  );
}
